const KEYS = Object.freeze(['subject', 'body']); const LIMITS = Object.freeze({ subject: 100, body: 65535 });
const plain = (v) => v !== null && typeof v === 'object' && !Array.isArray(v) && Object.getPrototypeOf(v) === Object.prototype;
export const normalizeCanonicalId = (v) => { const id = Number.isSafeInteger(v) ? String(v) : v; if (typeof id !== 'string' || !/^[1-9][0-9]{0,9}$/.test(id) || Number(id) > 4294967295) throw new TypeError('Invalid User Note target.'); return id; };
const normalizeAutosaveTarget = (v) => (v === null || (typeof v === 'string' && /^p1:[a-f0-9]{64}$/.test(v)) ? v : normalizeCanonicalId(v));
export const validatePayload = (v) => { if (!plain(v) || Object.keys(v).length !== 2 || !KEYS.every((k) => Object.hasOwn(v, k) && typeof v[k] === 'string' && Array.from(v[k]).length <= LIMITS[k])) throw new TypeError('Invalid User Note payload.'); return { subject: v.subject, body: v.body }; };
export default class NoteAutosaveAdapter {
  constructor({ descriptor, form, fields, editor, getCurrentEditor, eventFactory = (t) => new Event(t, { bubbles: true }) }) { if (!plain(descriptor) || !form || !plain(fields) || !fields.subject || !fields.body || !editor || typeof editor.getValue !== 'function' || typeof editor.setValue !== 'function' || typeof editor.subscribeChange !== 'function' || typeof getCurrentEditor !== 'function') throw new TypeError('Invalid Note adapter.'); this.descriptor = Object.freeze({ ...descriptor, targetId: normalizeAutosaveTarget(descriptor.targetId) }); this.form = form; this.fields = { ...fields }; this.editor = editor; this.getCurrentEditor = getCurrentEditor; this.eventFactory = eventFactory; this.baseline = null; this.callback = null; this.unsubscribeEditor = null; this.destroyed = false; this.suppressChanges = 0; this.listener = () => this.changed(); }
  getDescriptor() { return this.descriptor; } read() { return { subject: this.fields.subject.value, body: this.editor.getValue() }; } initializeBaseline() { this.assertCurrent(); this.baseline = this.read(); return this; }
  subscribe(cb) { if (typeof cb !== 'function' || this.callback || this.destroyed) throw new TypeError('Invalid Note subscription.'); if (!this.baseline) this.initializeBaseline(); this.callback = cb; ['input', 'change'].forEach((t) => this.fields.subject.addEventListener(t, this.listener)); this.unsubscribeEditor = this.editor.subscribeChange(this.listener); if (typeof this.unsubscribeEditor !== 'function') throw new TypeError('Invalid editor subscription.'); return () => this.unsubscribe(); }
  capture() { this.assertCurrent(); this.baseline = this.read(); return { ...this.baseline }; }
  apply(payload) { const next = validatePayload(payload); this.assertCurrent(); const previous = this.read(); this.suppressChanges += 1; try { this.fields.subject.value = next.subject; this.editor.setValue(next.body); this.fields.subject.dispatchEvent(this.eventFactory('input')); this.fields.subject.dispatchEvent(this.eventFactory('change')); this.baseline = this.read(); } catch (error) { this.fields.subject.value = previous.subject; this.editor.setValue(previous.body); this.baseline = previous; throw error; } finally { this.suppressChanges -= 1; } }
  changed() { if (this.suppressChanges || !this.callback || !this.isCurrent()) return; const next = this.read(); if (KEYS.every((k) => this.baseline?.[k] === next[k])) return; this.baseline = next; this.callback(); }
  isCurrent() { return !this.destroyed && this.form?.isConnected && this.fields.subject?.isConnected && this.fields.body?.isConnected && this.form.contains(this.fields.subject) && this.form.contains(this.fields.body) && this.getCurrentEditor(this.fields.body.id) === this.editor; } assertCurrent() { if (!this.isCurrent()) throw new Error('Note form is stale.'); }
  unsubscribe() { if (!this.callback) return; ['input', 'change'].forEach((t) => this.fields.subject.removeEventListener(t, this.listener)); this.unsubscribeEditor?.(); this.unsubscribeEditor = null; this.callback = null; } destroy() { if (this.destroyed) return; this.unsubscribe(); this.destroyed = true; this.form = null; this.fields = null; this.editor = null; }
}
export { KEYS as PAYLOAD_KEYS, LIMITS as MAXIMUM_LENGTHS };
