const PAYLOAD_KEYS = Object.freeze(['title', 'note', 'description', 'version_note', 'metadesc', 'metakey']);
const TEXT_KEYS = Object.freeze(PAYLOAD_KEYS.filter((key) => key !== 'description'));
const LIMITS = Object.freeze({ title: 255, note: 255, description: 65535, version_note: 255, metadesc: 300, metakey: 1024 });
const plain = (value) => value !== null && typeof value === 'object' && !Array.isArray(value) && Object.getPrototypeOf(value) === Object.prototype;
const normalizeCanonicalId = (value) => { const id = Number.isSafeInteger(value) ? String(value) : value; if (typeof id !== 'string' || !/^[1-9][0-9]{0,9}$/.test(id) || Number(id) > 2147483647) throw new TypeError('Invalid Category target.'); return id; };
const validatePayload = (payload) => { if (!plain(payload) || Object.keys(payload).length !== PAYLOAD_KEYS.length || !PAYLOAD_KEYS.every((key) => Object.hasOwn(payload, key) && typeof payload[key] === 'string' && Array.from(payload[key]).length <= LIMITS[key])) throw new TypeError('Invalid Category recovery payload.'); return Object.fromEntries(PAYLOAD_KEYS.map((key) => [key, payload[key]])); };
export default class CategoryAutosaveAdapter {
  constructor({ descriptor, form, fields, editor, getCurrentEditor, eventFactory = (type) => new Event(type, { bubbles: true }) }) { if (!plain(descriptor) || !form || !plain(fields) || !PAYLOAD_KEYS.every((key) => fields[key]) || !editor || typeof editor.getValue !== 'function' || typeof editor.setValue !== 'function' || typeof editor.subscribeChange !== 'function' || typeof getCurrentEditor !== 'function') throw new TypeError('Invalid Category adapter configuration.'); this.descriptor = Object.freeze({ context: descriptor.context, targetId: normalizeCanonicalId(descriptor.targetId), payloadSchemaVersion: descriptor.payloadSchemaVersion }); this.form = form; this.fields = { ...fields }; this.editor = editor; this.getCurrentEditor = getCurrentEditor; this.editorId = fields.description.id; this.eventFactory = eventFactory; this.baseline = null; this.callback = null; this.destroyed = false; this.suppress = 0; this.listeners = Object.fromEntries(TEXT_KEYS.map((key) => [key, () => this.changed()])); this.editorListener = () => this.changed(); }
  getDescriptor() { return this.descriptor; }
  initializeBaseline() { this.assertCurrent(); this.baseline = this.snapshot(); return this; }
  subscribe(callback) { if (typeof callback !== 'function' || this.callback || this.destroyed) throw new TypeError('Invalid Category subscription.'); this.callback = callback; TEXT_KEYS.forEach((key) => ['input', 'change'].forEach((type) => this.fields[key].addEventListener(type, this.listeners[key]))); this.unsubscribeEditor = this.editor.subscribeChange(this.editorListener); if (typeof this.unsubscribeEditor !== 'function') { this.unsubscribe(); throw new TypeError('Invalid Category editor subscription.'); } return () => this.unsubscribe(); }
  capture() { this.assertCurrent(); this.baseline = this.snapshot(); return { ...this.baseline }; }
  apply(payload) { const next = validatePayload(payload); this.assertCurrent(); const previous = this.snapshot(); this.suppress += 1; try { this.write(next); const applied = this.snapshot(); if (!PAYLOAD_KEYS.every((key) => applied[key] === next[key])) throw new Error('Category recovery failed.'); this.baseline = applied; } catch (error) { try { this.write(previous); this.baseline = previous; } catch (rollbackError) { Object.defineProperty(error, 'rollbackError', { value: rollbackError }); } throw error; } finally { this.suppress -= 1; } }
  snapshot() { return validatePayload({ ...Object.fromEntries(TEXT_KEYS.map((key) => [key, this.fields[key].value])), description: this.editor.getValue() }); }
  write(payload) { TEXT_KEYS.forEach((key) => { this.fields[key].value = payload[key]; this.fields[key].dispatchEvent(this.eventFactory('input')); this.fields[key].dispatchEvent(this.eventFactory('change')); }); this.editor.setValue(payload.description); }
  changed() { if (this.destroyed || this.suppress || !this.callback || !this.isCurrent()) return; let current; try { current = this.snapshot(); } catch { return; } if (PAYLOAD_KEYS.every((key) => current[key] === this.baseline?.[key])) return; this.baseline = current; this.callback(); }
  isCurrent() { return !this.destroyed && this.form?.isConnected && PAYLOAD_KEYS.every((key) => this.fields[key]?.isConnected && this.form.contains(this.fields[key])) && this.getCurrentEditor(this.editorId) === this.editor; }
  assertCurrent() { if (!this.isCurrent()) throw new Error('Category form or editor is stale.'); }
  unsubscribe() { if (!this.callback && !this.unsubscribeEditor) return; TEXT_KEYS.forEach((key) => ['input', 'change'].forEach((type) => this.fields[key].removeEventListener(type, this.listeners[key]))); this.callback = null; const unsubscribe = this.unsubscribeEditor; this.unsubscribeEditor = null; unsubscribe?.(); }
  destroy() { if (this.destroyed) return; this.unsubscribe(); this.destroyed = true; this.form = null; this.fields = null; this.editor = null; this.getCurrentEditor = null; }
}
export { LIMITS, PAYLOAD_KEYS, normalizeCanonicalId, validatePayload };
