const PAYLOAD_KEYS = Object.freeze(['title', 'description', 'from_stage_id', 'to_stage_id']);
const TEXT_KEYS = Object.freeze(['title', 'description']);
const RELATION_KEYS = Object.freeze(['from_stage_id', 'to_stage_id']);
const plain = (value) => value !== null && typeof value === 'object' && !Array.isArray(value) && Object.getPrototypeOf(value) === Object.prototype;
const normalizeCanonicalId = (value) => { const id = Number.isSafeInteger(value) ? String(value) : value; if (typeof id !== 'string' || !/^[1-9][0-9]{0,9}$/.test(id) || Number(id) > 2147483647) throw new TypeError('Invalid Transition target.'); return id; };
const normalizeAutosaveTarget = (value) => (value === null || (typeof value === 'string' && /^p1:[a-f0-9]{64}$/.test(value)) ? value : normalizeCanonicalId(value));
const parseRelation = (value, allowAny = false) => { if (allowAny && value === '-1') return -1; if (typeof value !== 'string' || !/^[1-9][0-9]{0,9}$/.test(value) || Number(value) > 2147483647) throw new TypeError('Invalid Transition relation.'); return Number(value); };
const validatePayload = (payload) => { if (!plain(payload) || Object.keys(payload).length !== PAYLOAD_KEYS.length || !PAYLOAD_KEYS.every((key) => Object.hasOwn(payload, key)) || typeof payload.title !== 'string' || Array.from(payload.title).length > 255 || typeof payload.description !== 'string' || Array.from(payload.description).length > 65535 || !Number.isInteger(payload.from_stage_id) || (payload.from_stage_id !== -1 && payload.from_stage_id <= 0) || payload.from_stage_id > 2147483647 || !Number.isInteger(payload.to_stage_id) || payload.to_stage_id <= 0 || payload.to_stage_id > 2147483647) throw new TypeError('Invalid Transition recovery payload.'); return Object.fromEntries(PAYLOAD_KEYS.map((key) => [key, payload[key]])); };
export default class TransitionAutosaveAdapter {
  constructor({ descriptor, form, fields, eventFactory = (type) => new Event(type, { bubbles: true }) }) { if (!plain(descriptor) || !form || !plain(fields) || !PAYLOAD_KEYS.every((key) => fields[key])) throw new TypeError('Invalid Transition adapter configuration.'); this.descriptor = Object.freeze({ context: descriptor.context, targetId: normalizeAutosaveTarget(descriptor.targetId), payloadSchemaVersion: descriptor.payloadSchemaVersion }); this.form = form; this.fields = { ...fields }; this.eventFactory = eventFactory; this.baseline = null; this.callback = null; this.destroyed = false; this.suppress = 0; this.listeners = Object.fromEntries(PAYLOAD_KEYS.map((key) => [key, () => this.changed()])); }
  getDescriptor() { return this.descriptor; }
  initializeBaseline() { this.assertCurrent(); this.baseline = this.snapshot(); return this; }
  subscribe(callback) { if (typeof callback !== 'function' || this.callback || this.destroyed) throw new TypeError('Invalid Transition subscription.'); this.callback = callback; PAYLOAD_KEYS.forEach((key) => ['input', 'change'].forEach((type) => this.fields[key].addEventListener(type, this.listeners[key]))); return () => this.unsubscribe(); }
  capture() { this.assertCurrent(); this.baseline = this.snapshot(); return { ...this.baseline }; }
  apply(payload) { const next = validatePayload(payload); this.assertCurrent(); const previous = this.snapshot(); this.suppress += 1; try { this.write(next); const applied = this.snapshot(); if (!PAYLOAD_KEYS.every((key) => applied[key] === next[key])) throw new Error('Transition recovery failed.'); this.baseline = applied; } catch (error) { try { this.write(previous); this.baseline = previous; } catch (rollbackError) { Object.defineProperty(error, 'rollbackError', { value: rollbackError }); } throw error; } finally { this.suppress -= 1; } }
  snapshot() { return validatePayload({ title: this.fields.title.value, description: this.fields.description.value, from_stage_id: parseRelation(this.fields.from_stage_id.value, true), to_stage_id: parseRelation(this.fields.to_stage_id.value) }); }
  write(payload) { const values = { ...payload, from_stage_id: String(payload.from_stage_id), to_stage_id: String(payload.to_stage_id) }; for (const key of PAYLOAD_KEYS) { if (RELATION_KEYS.includes(key) && ![...this.fields[key].options].some((option) => option.value === values[key])) throw new TypeError('Transition relation is unavailable.'); this.fields[key].value = values[key]; this.fields[key].dispatchEvent(this.eventFactory('input')); this.fields[key].dispatchEvent(this.eventFactory('change')); } }
  changed() { if (this.destroyed || this.suppress || !this.callback || !this.isCurrent()) return; let current; try { current = this.snapshot(); } catch { return; } if (PAYLOAD_KEYS.every((key) => current[key] === this.baseline?.[key])) return; this.baseline = current; this.callback(); }
  isCurrent() { return !this.destroyed && this.form?.isConnected && PAYLOAD_KEYS.every((key) => this.fields[key]?.isConnected && this.form.contains(this.fields[key])); }
  assertCurrent() { if (!this.isCurrent()) throw new Error('Transition form is stale.'); }
  unsubscribe() { PAYLOAD_KEYS.forEach((key) => ['input', 'change'].forEach((type) => this.fields[key].removeEventListener(type, this.listeners[key]))); this.callback = null; }
  destroy() { if (this.destroyed) return; this.unsubscribe(); this.destroyed = true; this.form = null; this.fields = null; }
}
export { PAYLOAD_KEYS, RELATION_KEYS, TEXT_KEYS, normalizeCanonicalId, parseRelation, validatePayload };
