import assert from 'node:assert/strict';
import test from 'node:test';
import { parseInteger, validatePayload as validateNewsfeed } from '../../../../media_source/com_newsfeeds/src/newsfeed-autosave-adapter.es6.js';
import NewsfeedController, { validateConfiguration as validateNewsfeedConfiguration } from '../../../../media_source/com_newsfeeds/src/newsfeed-autosave-controller.es6.js';
import { parseRelation, validatePayload as validateTransition } from '../../../../media_source/com_workflow/src/transition-autosave-adapter.es6.js';
import TransitionController, { validateConfiguration as validateTransitionConfiguration } from '../../../../media_source/com_workflow/src/transition-autosave-controller.es6.js';

const endpoints = { initialize: 'initialize', preserve: 'preserve', detect: 'detect', read: 'read', discard: 'discard', prepareCanonicalAction: 'prepare', getCanonicalActionOutcome: 'outcome' };
class Element extends EventTarget { constructor(id) { super(); this.id = id; this.value = ''; this.isConnected = true; this.options = []; } }
class Form extends Element { constructor(id) { super(id); this.children = new Set(); this.mounts = { '[data-joomla-autosave-status-ui]': new Element('status'), '[data-joomla-autosave-recovery-ui]': new Element('recovery') }; Object.values(this.mounts).forEach((item) => this.children.add(item)); } contains(item) { return this.children.has(item); } querySelectorAll(selector) { return this.mounts[selector] ? [this.mounts[selector]] : []; } }
class Document extends EventTarget { constructor(form, fields) { super(); this.elements = new Map([[form.id, form], ...Object.values(fields).map((field) => [field.id, field])]); } getElementById(id) { return this.elements.get(id) || null; } }
class Editor { constructor() { this.value = ''; this.listeners = new Set(); } supportsChangeObservation() { return true; } getValue() { return this.value; } setValue(value) { this.value = value; } subscribeChange(listener) { this.listeners.add(listener); return () => this.listeners.delete(listener); } }
class Runtime { constructor(options, calls) { this.options = options; this.calls = calls; } start() { this.calls.detect += 1; this.unsubscribe = this.options.adapter.subscribe(() => { this.calls.preserve += 1; }); return this; } destroy() { this.unsubscribe?.(); this.options.adapter.destroy(); } }

const specs = [
  { Controller: NewsfeedController, key: 'com_newsfeeds.autosave.newsfeed', context: 'com_newsfeeds.newsfeed', formId: 'newsfeed-form', fields: ['name', 'description', 'link', 'version_note', 'numarticles', 'cache_time', 'metadesc', 'metakey'], editor: true },
  { Controller: TransitionController, key: 'com_workflow.autosave.transition', context: 'com_workflow.transition', formId: 'workflow-form', fields: ['title', 'description', 'from_stage_id', 'to_stage_id'] },
];
const fixture = (spec) => { const form = new Form(spec.formId); const fields = Object.fromEntries(spec.fields.map((key) => [key, new Element(`jform_${key}`)])); Object.values(fields).forEach((field) => form.children.add(field)); if (spec.context === 'com_newsfeeds.newsfeed') { fields.numarticles.value = '5'; fields.cache_time.value = '3600'; } else { fields.from_stage_id.value = '-1'; fields.to_stage_id.value = '2'; fields.from_stage_id.options = [{ value: '-1' }, { value: '1' }]; fields.to_stage_id.options = [{ value: '2' }]; } const editor = new Editor(); const calls = { detect: 0, preserve: 0 }; const runtimes = []; const configuration = { enabled: true, context: spec.context, targetId: '7', payloadSchemaVersion: 1, formId: spec.formId, fieldIds: Object.fromEntries(spec.fields.map((key) => [key, `jform_${key}`])) }; const options = { documentSource: new Document(form, fields), optionsReader: (key, fallback) => (key === spec.key ? configuration : key === 'com_autosave.runtime' ? { endpoints } : key === 'csrf.token' ? 'token' : fallback), apiClientFactory: () => ({}), runtimeFactory: (runtimeOptions) => { const runtime = new Runtime(runtimeOptions, calls); runtimes.push(runtime); return runtime; }, coordinatorFactory: () => ({ start() { return this; }, destroy() {} }), presenterFactory: () => ({ destroy() {} }) }; if (spec.editor) options.editorRegistry = { get: () => editor, subscribeLifecycle: () => () => {} }; return { calls, controller: new spec.Controller(options), fields, runtimes }; };

test('canonical relation payload contracts reject unsafe types and extra relations', () => {
  const newsfeed = { name: '', description: '', link: '', version_note: '', numarticles: 5, cache_time: 3600, metadesc: '', metakey: '' };
  const transition = { title: '', description: '', from_stage_id: -1, to_stage_id: 2 };
  assert.deepEqual(validateNewsfeed(newsfeed), newsfeed); assert.deepEqual(validateTransition(transition), transition);
  assert.equal(parseInteger('4294967295'), 4294967295); assert.throws(() => parseInteger('05'), TypeError);
  assert.equal(parseRelation('-1', true), -1); assert.throws(() => parseRelation('-2', true), TypeError);
  assert.throws(() => validateNewsfeed({ ...newsfeed, catid: 3 }), TypeError); assert.throws(() => validateTransition({ ...transition, workflow_id: 4 }), TypeError);
});
test('configuration is exact and ID zero remains native fallback', () => { for (const spec of specs) { const config = { enabled: true, context: spec.context, targetId: '7', payloadSchemaVersion: 1, formId: spec.formId, fieldIds: Object.fromEntries(spec.fields.map((key) => [key, `jform_${key}`])) }; const validate = spec.editor ? validateNewsfeedConfiguration : validateTransitionConfiguration; assert.equal(validate(config).targetId, '7'); assert.throws(() => validate({ ...config, targetId: '0' }), TypeError); } });
for (const spec of specs) test(`${spec.context} starts one runtime and observes approved fields`, async () => { const current = fixture(spec); current.controller.start(); await current.controller.reconcile(); await current.controller.reconcile(); assert.equal(current.runtimes.length, 1); assert.equal(current.calls.detect, 1); current.fields[spec.fields[0]].value = 'Changed'; current.fields[spec.fields[0]].dispatchEvent(new Event('input')); assert.equal(current.calls.preserve, 1); current.controller.destroy(); });
